### ISSUE TITLE
Libreria Solver

### ISSUE THREAD

**Issue by cuesto** [stevensotelo/ConstraintProgramming#1]
Puedes por favor proporcionar un link para descargar la librería de solver?

**Comment by stevensotelo** [comment]
Hola

Microsoft tuvo hasta diciembre disponible la descarga de una versión gratis en http://blogs.msdn.com/b/solverfoundation/ , sin embargo la versión 3.1 que fue la última versión lanzada por ellos, tuvo soporte hasta el 2012 y eliminaron el blog (Apenas me doy cuenta de eso). Existen dos formas de acceder al API:
1. A través de tu suscripción a MSDN
2. http://www.gurobi.com/

Es una lastima que ya no vaya a continuar este producto, sin embargo, van a tomar esta API e integrarla con un nuevo conjunto de herramientas, de la cual estamos al tanto para probarla. Te dejo este link adicionalmente:

https://msdn.microsoft.com/en-us/library/ff524499(v=vs.93).aspx
